channels:
  - conda-forge
dependencies:
  - dask==2021.2.0
  - dask-gateway==0.9.0
  - distributed
  - dask-labextension
  - scipy==1.5.3
  - nibabel==2.5.1
  - h5py==2.9.0
  - matplotlib==3.1.0
  - xarray==0.16.2
  - numba==0.43.1
  - scikit-image==0.15.0
  - s3fs==0.3.4
  - zarr==2.3.1
  - seaborn==0.9.0
  - tqdm==4.32.1
  - plotly==3.9.0
  - ipywidgets==7.4.2
  - jupyterlab==1.1.2
  - awscli==1.16.249
  - pip==19.2.3
  - xvfbwrapper
  - python-graphviz
  - scikit-learn==0.22.1
  - statsmodels
  - xgboost
  - shap
  - dipy
  - pip:
    - pyAFQ
    - afqinsight
    - git+https://github.com/dhuppenkothen/entrofy.git@35b2482
    - neuropythy
